In [1]:
import numpy as np


In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print('Honesto')


[1 2 3 4 5]
Honesto


In [3]:
arr1 = [[1,2,3,4,5], [6,7,8,9,0]]
print(arr1, type(arr1))
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(arr2, type(arr2))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]] <class 'list'>
[[1 2 3 4 5]
 [6 7 8 9 0]] <class 'numpy.ndarray'>


# Array Attributes
## Array Attributes
### Array Attributes
#### Array Attributes
##### Array Attributes
###### Array Attributes
- These are array attributes

### ndim

In [4]:
# Dimensions of an array
arr1 = np.array([1,2,3,4,5])
print(arr1.ndim)    # 1
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(arr2.ndim)    # 2

1
2


### shape: (row, columns)

In [5]:
# If it's a 1D array, it returns number of items
print(arr1.shape)
# 2D array: returns number of row and columns
print(arr2.shape)


(5,)
(2, 5)


### size
- Total number of elements in the array

In [6]:
print(arr1.size)
print(arr2.size)

5
10


### dtype
- returns the Data type of the array
- arrays can hold the value sof a single data type only - Homogenuous

In [7]:
arr1.dtype

dtype('int64')

### itemsize
- size of each element of the array in Bytes

In [8]:
print(arr1.itemsize)
print(arr2.itemsize)
arr3 = np.array([1.5, 2.3])
print(arr3.dtype)
print(arr3.itemsize)


8
8
float64
8


## Data Type Conversion
- Although Numpy automatically infers the data type of array elements but we can specify overwriting the infered data type


### Method 1: dtype parameter

In [9]:
arr = np.array([1.2, 2.2, 3.4, 5.6], dtype=np.float16)
print(arr.dtype)

float16


### Method 2: astype()

In [10]:
arr = np.array([1.2, 2.2, 3.4, 5.6])
arr = arr.astype(int)
print(arr)
arr = arr.astype(float)
print(arr)

[1 2 3 5]
[1. 2. 3. 5.]


### returns a list of variables and functions in a module/library/package

In [11]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [12]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

#### Check Numpy Version

In [13]:
np.__version__

'1.26.4'

## Creating and Initializing Arrays

### Creating arrays with built-in functions
#### Zeros | Ones | Full | Empty

In [3]:
zeros_arr = np.zeros((3,4))
print("Zeros:\n", zeros_arr)


ones_arr = np.ones((3,4))
print("Ones:\n", ones_arr)


full_arr = np.full((3,4), 5)
print("full:\n", full_arr)


empty_arr = np.empty((3,4))
print("empty:\n", empty_arr)

NameError: name 'np' is not defined

## Numerrical Sequences

### arange(start, end, step)

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### linspace()

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Identical Matrix

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(4) * 5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [19]:
arr = [[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]]

print(arr * 3)

[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


## Numpy Array with arithmetic Operators

In [20]:
arr = np.array([1,2,3,4,5])
print('Numpy Array Addition:')
print(arr + 3)
print('\nNumpy Array Subtraction:')
print(arr - 3)
print('\nNumpy Array Multiplication:')
print(arr * 3)
print('\nNumpy Array Divide:')
print(arr / 3)

lst = [1,2,3,4,5]
print('\nPython list Addition:')
print(lst + [3])
# only a list can be added with another list - not with any integer.

# print('\nPython list Subtraction:')   # not feasible
# print(lst - 3)
print('\nPython list Multiplication:')
print(lst * 3)
# print('\nPython list Division:')      # not feasible
# print(lst / 3)

Numpy Array Addition:
[4 5 6 7 8]

Numpy Array Subtraction:
[-2 -1  0  1  2]

Numpy Array Multiplication:
[ 3  6  9 12 15]

Numpy Array Divide:
[0.33333333 0.66666667 1.         1.33333333 1.66666667]

Python list Addition:
[1, 2, 3, 4, 5, 3]

Python list Multiplication:
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### Diagonal

In [21]:
np.diag([10, 20, 30, 40,50])

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

## Random Array

### seting up the Seed : seed()
- This maintains the reproducibility

In [22]:
np.random.seed(42)


In [23]:
# Creating a matrix of random numbers between 0 and 1
np.random.seed(0)
print(np.random.rand(2, 2))
print(np.random.rand(3, 3))

# With Normal Distribution mean = 0 and std = 1
print(np.random.randn(2, 2))
print(np.random.randn(3, 3))

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
[[0.4236548  0.64589411 0.43758721]
 [0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456]]
[[ 0.48431215  0.57914048]
 [-0.18158257  1.41020463]]
[[-0.37447169  0.27519832 -0.96075461]
 [ 0.37692697  0.03343893  0.68056724]
 [-1.56349669 -0.56669762 -0.24214951]]


In [24]:
# create an array of random integers
# np.random.randint(start, end, (row, column))
np.random.seed(42)
np.random.randint(1, 100, (3, 5))


array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75],
       [88, 24,  3, 22, 53]])

## Indexing and Slicing
- Indexing: positioning of each element or item in a string/list/dictionary
- Slicing: when we access multiple items at a time


In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,0] 
        #  0 1 2 3 4 5 6 7 8 9
print(numbers[:2])
print(numbers[5])


list2d = [[1,2,3], [4,5,6], [7,8,9]]
# Python: 2dlist[row][column]
print(list2d[2][1])

[1, 2]
6
8


In [36]:
arr = np.array(range(10, 101, 10))
print(arr)
print(arr[0])
print(arr[-1])


arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)
print(arr2d[2, 1])

[ 10  20  30  40  50  60  70  80  90 100]
10
100
[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


#### Slicing
- Syntax: array[start: end: step]

In [41]:
print(arr[1:4])
print(arr[:3])
print(arr[::2])   # [10, 30, 50, 70, 90]

[20 30 40]
[10 20 30]
[10 30 50 70 90]


### Indexing
- arr2d[row, column]

### Slicing
- arr2d[[start: end: step], [start:end:step]]

In [52]:
print(arr2d)
print(arr2d[0:2, 0:2])
# [[1,2],
#  [4,5]]


print(arr2d[0:2, 1:3])
# [[2 3]
#  [5 6]]



print(arr2d[1:3, 1:3])
# [[5,6], 
#  [8,9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[5 6]
 [8 9]]


In [ ]:
arr2 = np.array([
    [10, 20, 30, 40, 50],
    [101, 202, 303, 404, 505],
    [100, 200, 300, 400, 500],
    [111, 222, 333, 444, 555],
    [111, 121, 131, 141, 151]
    ])

print(arr2[1:4, 1:3])
'''
[[202 303]
 [200 300]
 [222 333]]
'''

# get all the records from last column
print(arr2[:, 4:])


# to get all the rows except the last row
print(arr2[:-1])


# to get the last row
print(arr2[-1])

[[202 303]
 [200 300]
 [222 333]]
[[ 50]
 [505]
 [500]
 [555]
 [151]]
[[ 10  20  30  40  50]
 [101 202 303 404 505]
 [100 200 300 400 500]
 [111 222 333 444 555]]
[111 121 131 141 151]


## Boolean Indexing
- selects the elements that satisfies a condition

In [ ]:
arr = np.arange(1, 20, 2)
print(arr)
mask = arr > 10
print(mask)
print("Filtered values: ", arr[mask])


[ 1  3  5  7  9 11 13 15 17 19]
[False False False False False  True  True  True  True  True]
Filtered values:  [11 13 15 17 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
# get all the even numbers from a list of numbers
arr = np.arange(1, 20)
print(arr)
arr = np.arange(1,20)
print(arr)
mask = arr % 2 == 0
print("Filtered evens: ", arr[mask])

AttributeError: module 'numpy' has no attribute 'arange'